version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3010:3000'
    networks:
      - monitoring
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-config:/etc/grafana
    depends_on:
      - loki
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3110:3100'
    networks:
      - monitoring
    volumes:
      - ./loki-data:/data/loki
      - ./loki-config:/etc/loki
    command: '-config.file=/etc/loki/loki-local-config.yaml'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      - monitoring
    volumes:
      - ./prometheus-data:/prometheus/data
      - ./prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--web.enable-lifecycle'

networks:
  monitoring:
