version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3010:3000'
    networks:
      - monitoring
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-config:/etc/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/plugins:/etc/grafana/provisioning/plugins
      - ./grafana-provisioning/notifiers:/etc/grafana/provisioning/notifiers
      - ./grafana-provisioning/alerting:/etc/grafana/provisioning/alerting
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - loki
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3110:3100'
    networks:
      - monitoring
    volumes:
      - ./loki-data:/data/loki
      - ./loki-config:/etc/loki
    command: '-config.file=/etc/loki/loki-local-config.yaml'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      - monitoring
    volumes:
      - ./prometheus-data:/prometheus/data
      - ./prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--web.enable-lifecycle'
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring
    restart: unless-stopped

networks:
  default:
    name: monitoring
