version: '3.8'

services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - ${GRAFANA_HOST_PORT}:3000
    environment:
      - GF_LOG_FRONTEND_PROVIDER=grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-config:/etc/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/plugins:/etc/grafana/provisioning/plugins
      - ./grafana-provisioning/notifiers:/etc/grafana/provisioning/notifiers
      - ./grafana-provisioning/alerting:/etc/grafana/provisioning/alerting
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-plugins-bundled:/usr/share/grafana/plugins-bundled
    networks:
      - monitoring
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    ports:
      - ${PROMETHEUS_HOST_PORT}:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus-data:/prometheus/data
      - ./prometheus-config:/etc/prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    container_name: node-exporter
    ports:
      - ${NODE_EXPORTER_HOST_PORT}:9100
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring
    restart: unless-stopped

  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_STACK_VERSION}
    container_name: elk_setup
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTICSEARCH_PASSWORD} == x ]; then
          echo "Set the ELASTICSEARCH_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        echo "Waiting for Elasticsearch availability";
        until curl -s http://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting built-in user passwords";
        until echo "elastic:${ELASTICSEARCH_PASSWORD}" > /tmp/passwords && echo "kibana_system:${KIBANA_PASSWORD}" >> /tmp/passwords && /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -b --url http://elasticsearch:9200 -f --input-file /tmp/passwords; do sleep 10; done;
        echo "All done!";
      '

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_STACK_VERSION}
    container_name: elasticsearch
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=true
      - xpack.license.self_generated.type=${ELASTICSEARCH_LICENSE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - monitoring

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_STACK_VERSION}
    container_name: logstash
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ./logstash-config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash-pipeline:/usr/share/logstash/pipeline:ro,Z
    networks:
      - monitoring
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_STACK_VERSION}
    container_name: kibana
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - ./kibana-data:/usr/share/kibana/data
    networks:
      - monitoring
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local

networks:
  monitoring:
