version: '3.8'

services:
  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    ports:
      - '3010:3000'
    networks:
      - monitoring
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-config:/etc/grafana
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/plugins:/etc/grafana/provisioning/plugins
      - ./grafana-provisioning/notifiers:/etc/grafana/provisioning/notifiers
      - ./grafana-provisioning/alerting:/etc/grafana/provisioning/alerting
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-plugins-bundled:/usr/share/grafana/plugins-bundled
    environment:
      - GF_LOG_FRONTEND_PROVIDER=grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.37.7
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      - monitoring
    volumes:
      - ./prometheus-data:/prometheus/data
      - ./prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--web.enable-lifecycle'

  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - monitoring
    ports:
      - "9200:9200"
      - "9300:9300"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - monitoring
    depends_on:
      - elasticsearch

networks:
  monitoring:
