global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['culinary-blog-nginx-exporter:9113']

  - job_name: 'mysql-exporter'
    static_configs:
    - targets: ['culinary-blog-mysql-exporter:9104']
